language: python
python:
  - "2.7"
before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
  - conda config --add channels conda-forge

  # add for profile
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq


install:
# add for profile
 - sudo apt-get install -qq g++-4.8
 - export CXX="g++-4.8"
 - pip install nose-cprof
 - pip install properform

  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy nose future
  - pip install -v .
script:
  - nosetests tests --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_autograd_c1449262c5_4
  - python -m properform Push 47.88.50.110:15554 asdf_autograd_c1449262c5_4 ./profile_autograd_c1449262c5_4
 #2017-09-18 15:35:24 modified at 0 #2017-09-18 15:35:29 modified at 1 #2017-09-18 15:35:33 modified at 2 #2017-09-18 15:35:38 modified at 3 #2017-09-18 15:35:42 modified at 4