language: python
python:
  - "2.7"
env:
  - USE_CYTHON=1
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform

  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy cython nose future
  - pip install -v .
script:
   - nosetests tests --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_autograd_0c1c706afc_3
  - python -m properform Push 47.88.50.110:15554 asdf_autograd_0c1c706afc_3 ./profile_autograd_0c1c706afc_3
 #2017-09-18 16:41:40 modified at 0 #2017-09-18 16:41:44 modified at 1 #2017-09-18 16:41:48 modified at 2 #2017-09-18 16:41:53 modified at 3